services:
  database:
    image: postgres:13
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
